# Generated by Django 2.2.12 on 2024-02-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsAgency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=64),
        ),
    ]
